esphome:
  name: test-switch
  friendly_name: test-switch

rtl87xx:
  board: wbr3
  family: rtl8720c
  framework:
    version: 0.0.0
    source: https://github.com/libretiny-eu/libretiny.git#feature/realtek-update
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "your-encryption-key"

#OTA doesn't work on the platform yet
ota:
  - platform: esphome
    password: "ota-password"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test-Switch Fallback Hotspot"
    password: "beiklW9AIX49"

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO19
      inverted: true
    id: main_switch
    internal: true
    on_click:
      min_length: 50ms
      max_length: 350ms
      then:
      - light.toggle: night_led

output:
  - platform: libretiny_pwm
    pin: GPIO2
    frequency: 1000 Hz
    id: white_led

light:
  - platform: status_led
    id: status
    pin: GPIO4
  - platform: monochromatic
    id: night_led
    output: white_led

uart:
  tx_pin: GPIO14
  rx_pin: GPIO13
  baud_rate: 9600
  debug:

# captive_portal causes the compillation to fail on RTL8720CM
# captive_portal:

